### ISSUE TITLE
Issues of federated-gans

### ISSUE THREAD

**Issue by wangclin** [google-research/federated#44] opened 2021-10-14 08:44 UTC
pip install absl-py
pip install attr
pip install dm-tree
pip install numpy
pip install Pillow
pip install tensorboard
pip install tensorflow
pip install tensorflow-federated
pip install tensorflow-gan
pip install tensorflow-privacy

could you please give a requirement doc or specific version of each library?

I met a lot of version issues about tensorflow and others.

Thanks.

**Comment by nightldj** [comment] 2021-11-11 03:19
Close this for now. Feel free to re-open if the problem is not solved.

**Closed by nightldj** 2021-11-11 03:19 UTC
