### ISSUE TITLE
TimeoutError: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by JerryLeeljr** [google-research/federated#38] opened 2021-05-24 14:21 UTC
Hi, thanks for your share, I tried to run your code as Example usage do:

```
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=100
 --client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20
 --server_optimizer=sgd --server_learning_rate=1.0 --clients_per_round=10
 --client_epochs_per_round=1 --experiment_name=emnist_fedavg_experiment

```
But I got following errors. Could you help me fix them? Thanks.

![2021-05-24 22-14-35 的屏幕截图](https://user-images.githubusercontent.com/43852762/119361437-40272180-bcde-11eb-93e1-0610efce742b.png)
![2021-05-24 22-13-55 的屏幕截图](https://user-images.githubusercontent.com/43852762/119361424-3bfb0400-bcde-11eb-92a6-13e90fcc8f2a.png)

**Comment by PeppaCat** [comment] 2021-05-30 12:04
What is the python and tf version you used?

**Comment by JerryLeeljr** [comment] 2021-06-03 16:27
> What is the python and tf version you used?

python 3.8.5 
tf 2.5.0 
tensorflow_federated 0.19.0
ubuntu 20.04

**Comment by wennanzhu** [comment] 2021-06-21 12:33
It seems the error is from "emnist_train, _ = tff.simulation.datasets.emnist.load_data(only_digits=False)". Would you try to run only this line to see if the same error appears?

**Comment by nightldj** [comment] 2021-07-09 06:11
Seems to be the /optimization project, Zach, could you take a look? Thanks.

**Comment by zcharles8** [comment] 2021-07-09 15:54
As @wennanzhu noted above, this seems to be caused by the call to `tff.simulation.datasets.emnist.load_data`. @JerryLeeljr could you see if you face the same error just on this call in a reproducible manner?

**Comment by zcharles8** [comment] 2021-07-28 23:46
Hi @JerryLeeljr. I'm closing this issue since it has not had any updates in a while, and I have not been able to reproduce this bug. If you are still running into this issue, feel free to re-open this or file a bug on TFF (as it seems to be entirely a TFF issue if I understand correctly).

**Closed by zcharles8** 2021-07-28 23:46 UTC
